import type { RentalCompany } from "./types"

// TODO: Reemplazar con datos de Supabase
export const mockCompanies: RentalCompany[] = [
  {
    id: "localiza-argentina",
    name: "Localiza Argentina",
    city: "Buenos Aires",
    province: "Buenos Aires",
    rating: 4.7,
    reviewCount: 156,
    logoUrl: "/placeholder.svg?height=64&width=64",
    coverImageUrl: "/placeholder.svg?height=200&width=400",
    address: "Av. Corrientes 1234, Buenos Aires",
    phone: "+54 11 4567-8900",
    website: "https://localiza.com.ar",
    whatsapp: "5491123456789",
    gmapsUrl: "#",
    services: ["Alquiler por día", "Alquiler por semana", "Seguro completo"],
    category: "Agencia de alquiler de automóviles",
    isOpen: true,
    businessHours: {
      monday: "8:00 - 20:00",
      tuesday: "8:00 - 20:00",
      wednesday: "8:00 - 20:00",
      thursday: "8:00 - 20:00",
      friday: "8:00 - 20:00",
      saturday: "9:00 - 18:00",
      sunday: "10:00 - 16:00",
    },
    features: ["Entrega a domicilio", "GPS incluido", "Seguro premium"],
  },
  {
    id: "hertz-argentina",
    name: "Hertz Argentina",
    city: "Córdoba",
    province: "Córdoba",
    rating: 4.5,
    reviewCount: 203,
    logoUrl: "/placeholder.svg?height=64&width=64",
    coverImageUrl: "/placeholder.svg?height=200&width=400",
    address: "Av. Colón 567, Córdoba",
    phone: "+54 351 456-7890",
    website: "https://hertz.com.ar",
    whatsapp: "5493514567890",
    gmapsUrl: "#",
    services: ["Alquiler corporativo", "Asistencia en ruta", "Flota moderna"],
    category: "Agencia de alquiler de automóviles",
    isOpen: true,
    businessHours: {
      monday: "7:00 - 21:00",
      tuesday: "7:00 - 21:00",
      wednesday: "7:00 - 21:00",
      thursday: "7:00 - 21:00",
      friday: "7:00 - 21:00",
      saturday: "8:00 - 19:00",
      sunday: "9:00 - 17:00",
    },
    features: ["Aeropuerto", "Autos premium", "Servicio 24hs"],
  },
  {
    id: "avis-mendoza",
    name: "Avis Mendoza",
    city: "Mendoza",
    province: "Mendoza",
    rating: 4.3,
    reviewCount: 89,
    logoUrl: "/placeholder.svg?height=64&width=64",
    coverImageUrl: "/placeholder.svg?height=200&width=400",
    address: "San Martín 890, Mendoza",
    phone: "+54 261 789-0123",
    website: "https://avis.com.ar",
    whatsapp: "5492617890123",
    gmapsUrl: "#",
    services: ["Alquiler para turismo", "Traslado al aeropuerto", "Rutas de vino"],
    category: "Agencia de alquiler de automóviles",
    isOpen: false,
    businessHours: {
      monday: "8:00 - 20:00",
      tuesday: "8:00 - 20:00",
      wednesday: "8:00 - 20:00",
      thursday: "8:00 - 20:00",
      friday: "8:00 - 20:00",
      saturday: "9:00 - 18:00",
      sunday: "Cerrado",
    },
    features: ["Turismo", "Autos 4x4", "Guías especializadas"],
  },
  {
    id: "europcar-bariloche",
    name: "Europcar Bariloche",
    city: "San Carlos de Bariloche",
    province: "Río Negro",
    rating: 4.8,
    reviewCount: 312,
    logoUrl: "/placeholder.svg?height=64&width=64",
    coverImageUrl: "/placeholder.svg?height=200&width=400",
    address: "Av. del Vado 452, San Carlos de Bariloche",
    phone: "+54 294 441-5170",
    website: "https://europcar.com.ar",
    whatsapp: "5492944415170",
    gmapsUrl: "#",
    services: ["Cadenas para nieve", "Vehículos de invierno", "Turismo aventura"],
    category: "Agencia de alquiler de automóviles",
    isOpen: true,
    businessHours: {
      monday: "8:00 - 20:00",
      tuesday: "8:00 - 20:00",
      wednesday: "8:00 - 20:00",
      thursday: "8:00 - 20:00",
      friday: "8:00 - 20:00",
      saturday: "9:00 - 19:00",
      sunday: "10:00 - 18:00",
    },
    features: ["Equipamiento nieve", "Autos 4x4", "Aventura"],
  },
  // Agregar más empresas para completar la cuadrícula
  {
    id: "km0-rent-bariloche",
    name: "Km 0 Rent a Car",
    city: "San Carlos de Bariloche",
    province: "Río Negro",
    rating: 4.8,
    reviewCount: 202,
    logoUrl: "/placeholder.svg?height=64&width=64",
    coverImageUrl: "/placeholder.svg?height=200&width=400",
    address: "191 Palacios, San Carlos de Bariloche",
    phone: "+54 294 453-7852",
    website: "https://km0rentacar.com.ar",
    whatsapp: "5492944537852",
    gmapsUrl: "#",
    services: ["Renta de Autos en Bariloche", "Mejor precio", "Autos nuevos"],
    category: "Agencia de alquiler de automóviles",
    isOpen: true,
    businessHours: {
      monday: "8:00 - 20:00",
      tuesday: "8:00 - 20:00",
      wednesday: "8:00 - 20:00",
      thursday: "8:00 - 20:00",
      friday: "8:00 - 20:00",
      saturday: "9:00 - 18:00",
      sunday: "10:00 - 16:00",
    },
    features: ["Autos 0km", "Precios competitivos", "Atención personalizada"],
  },
  {
    id: "auka-rent-bariloche",
    name: "Auka Rent a Car",
    city: "San Carlos de Bariloche",
    province: "Río Negro",
    rating: 5.0,
    reviewCount: 712,
    logoUrl: "/placeholder.svg?height=64&width=64",
    coverImageUrl: "/placeholder.svg?height=200&width=400",
    address: "Av. del Vado 452, R8402 San Carlos de Bariloche",
    phone: "+54 294 441-5170",
    website: "https://aukarentacar.com.ar",
    whatsapp: "5492944415170",
    gmapsUrl: "#",
    services: ["Alquiler de coches", "Equipamiento completo", "Servicio premium"],
    category: "Agencia de alquiler de coches",
    isOpen: true,
    businessHours: {
      monday: "8:00 - 20:00",
      tuesday: "8:00 - 20:00",
      wednesday: "8:00 - 20:00",
      thursday: "8:00 - 20:00",
      friday: "8:00 - 20:00",
      saturday: "9:00 - 19:00",
      sunday: "10:00 - 18:00",
    },
    features: ["Calificación perfecta", "Servicio excepcional", "Flota premium"],
  },
]

export function getCompaniesByProvince(province: string): RentalCompany[] {
  return mockCompanies.filter((company) => company.province === province)
}

export const provinces = [
  { name: "Buenos Aires", companies: getCompaniesByProvince("Buenos Aires") },
  { name: "Córdoba", companies: getCompaniesByProvince("Córdoba") },
  { name: "Mendoza", companies: getCompaniesByProvince("Mendoza") },
  { name: "Río Negro", companies: getCompaniesByProvince("Río Negro") },
]
